export * from './CartPage';
export * from './Contacts';
export * from './FavouritesPage';
export * from './HomePage';
export * from './NotFoundPage';
export * from './ProductPage';
export * from './ProductPageImage';
export * from './ProductsPage';
export * from './Rights';
