export enum PATH {
  Main = 'main',
  Home = 'home',
  Phones = 'phones',
  Phone = 'phoneId',
  Tablet = 'tabletId',
  Tablets = 'tablets',
  Accessories = 'accessories',
  Accessory = 'accessoryId',
  Favourites = 'favourites',
  Cart = 'cart',
  Order = 'order',
  Error = 'error',
  Contacts = 'contacts',
  Rights = 'rights',
  Success = 'successOrder',
  Orders = 'orders',
}
